### PR TITLE
Use ParkingSpace to set parkedAt on channel

### PR DESCRIPTION
**Pull request by discardedwutu**
Addresses Issue Report #264 

Use ParkingSpace to set parkedAt on channel instead of 'Exten'. Falls back to
Exten if ParkingSpace is null for some reason (most likely because we are on
an older version of Asterisk).

Also, changes setParkedAt to include a parkinglot name. This can be retrieved
from the Asterisk channel with getParkingLot(). Between getParkedAt() and
getParkingLot() you can get all the arguments needed to use the ParkedCall
dialplan application on any parked call.

### CODE REVIEW

**Comment by bsutton** [comment]
We are about to create a V3 branch, hopefully later this week. I think it would be more appropriate to put this patch on the V3 branch.

**Comment by discardedwutu** [comment]
Alright, I'll be sure to post a V3 version once that goes online.

**Comment by discardedwutu** [comment]
Any updates on the version 3 branch? Still not seeing it listed amid the repositories.

**Comment by bsutton** [comment]
v3 has been created!

**Comment by discardedwutu** [comment]
Hey, I don't use github a ton, so I'm not 100% sure on best practices for this stuff, but I merged the master here back to my fork and it looks like that commit is showing up on this pull request, so I think we are square here for now? Let me know if it's reviewable in its current state if you can. Appreciate it!

**Comment by bsutton** [comment]
thanks for the patch.

**Pull request merged**
