### PR TITLE
Support of Asterisk 18 version

### PR DESCRIPTION
**Pull request by aabreu-fuze**

### CODE REVIEW

**Comment by timo-klarshift** [comment]
We are really looking forward to get this merged :) Is there anything I can help with ?

**Comment by bsutton** [comment]
I would try to get tiers merged Monday.

We are looking for additional administrator..

**Comment by timo-klarshift** [comment]
> We are looking for additional administrator..

Are you saying your are looking for project maintainers ?

**Comment by bsutton** [comment]
Yes

**Pull request merged**
