### PR TITLE
Add new property SL2

### PR DESCRIPTION
**Pull request by scgm11**
sl2 is included on asterisk master branch

### CODE REVIEW

**Comment by scgm11** [comment]
any comments?

**Comment by scgm11** [comment]
??

**Comment by bsutton** [comment]
sorry for the lateness.

**Comment by bsutton** [comment]
Are you interested in becoming a committer?

**Comment by scgm11** [comment]
you can give me access yes, anyway we should still be doing pull request to code review before merge, some time ago I used to send the patches to stefan

**Pull request merged**
