### PR TITLE
race conditions during reconnect

### PR DESCRIPTION
**Pull request by elara-leitstellentechnik**
Fixes a race condition during reconnecting while simultaniously disconnecting/connecting

Solution:
- synchronize all state changes
- synchronize all crucial state checks

### CODE REVIEW

**Comment by bsutton** [comment]
Not certain I'm happy with this.
You have the sync block in the while loop, which means that for each iteration of the loop you release the sync which means another reconnect can come through and additional reconnect threads start.
So what was the original race condition?
Also not in love with using sync(this). Its very aggressive. We tend to prefer using a 'semaphore' from the concurrency classes these days.
Also don't like the 'while(true)', somewhat in principle but it is a horrible thing.

**Comment by bsutton** [comment]
We probably need to see some test cases around this code.
Its a super critical piece of code and if we get it wrong it will break a lot of systems.

**Comment by elara-leitstellentechnik** [comment]
Hi Brett, thanks a lot for reviewing our PR. 

The colleague who wrote this code will only be back in a couple of days but I was the reviewer so let me try and explain the rationale. 

The original race condition is that the decision of whether or not connect() is called was made e.g. in the condition of the while loop, which was not synchronized. So the connection state might change to "connected" after the condition evaluation, but connect() would be called nevertheless. 
The connect method is synchronized, which is technically equivalent to synchronized(this), so
the situation you are describing (multiple reconnect threads running) is possible with the current code (connect() is synchronized, but you release the sync in each while iteration!).
The while(true) part of the change was introduced to be able to put the decision of whether or not to call connect() and the actual call to connect() into one sync block.

So really this change is aiming at preventing the issue to have multiple reconnect threads running. 
After the proposed change, a second iteration of the loop would check the state within the sync block and thus reliably recognize the reconnecting state. The spawning of an additional thread would be prevented.

We certainly agree with your comments on sync(this) and such, but the idea was to introduce the least possible technical change while still fixing the race condition...

Hope this makes sense.

**Comment by bsutton** [comment]
So as I understand it sync on a method just syncs access to the method
whilst sync this restricts access to any other call using sync this.
In this case I don't think it's critical but current best practice
recommends not using sync as it has wholes so we avoid it.
The real issue appears that you don't stop multiple reconnect threads
started as each loop of the while releases the sync which can allow another
reconnect through.


On 8 Sep. 2017 6:50 pm, "elara-leitstellentechnik" <notifications@github.com>
wrote:

Hi Brett, thanks a lot for reviewing our PR.

The colleague who wrote this code will only be back in a couple of days but
I was the reviewer so let me try and explain the rationale.

The original race condition is that the decision of whether or not
connect() is called was made e.g. in the condition of the while loop, which
was not synchronized. So the connection state might change to "connected"
after the condition evaluation, but connect() would be called nevertheless.
The connect method is synchronized, which is technically equivalent to
synchronized(this), so
the situation you are describing (multiple reconnect threads running) is
possible with the current code (connect() is synchronized, but you release
the sync in each while iteration!).
The while(true) part of the change was introduced to be able to put the
decision of whether or not to call connect() and the actual call to
connect() into one sync block.

So really this change is aiming at preventing the issue to have multiple
reconnect threads running.
After the proposed change, a second iteration of the loop would check the
state within the sync block and thus reliably recognize the reconnecting
state. The spawning of an additional thread would be prevented.

We certainly agree with your comments on sync(this) and such, but the idea
was to introduce the least possible technical change while still fixing the
race condition...

Hope this makes sense.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/asterisk-java/asterisk-java/pull/214#issuecomment-328043861>,
or mute the thread

**Comment by elara-leitstellentechnik** [comment]
Hmm, our understanding differs then. According to the [documentation](https://docs.oracle.com/javase/tutorial/essential/concurrency/locksync.html) synchronized(this) acquires the same so-called "intrinsic lock" of an object that is acquired by calling a synchronized method.
 
Again the "real issue" you are describing is acually present in the current code and addressed by the proposed change. 
Assuming my understanding of synchronized as described above is correct maybe the following way of looking at it illustrates this further. 
connect() is a synchronized method, so it would be technically equivalent to remove the synchronized keyword from the method and wrap the method call in a synchronized(this) block.
Then the difference to the code change we propose would only be that the connection state check and the call to doLogin (which entails connection state changes) is moved into the synchronized block.

This in turn ensures that a new Thread is spawned if and only if the connection state requires it.

**Comment by bsutton** [comment]
I stand corrected on the sync blocks.

It sounds like your proposal to move the test inside the sync block will
resolve the whole.

Are you able to submit a test case along with the code changes?

**Comment by elara-leitstellentechnik** [comment]
I am afraid not. We haven't been able to demonstrate the problem in JUnit Tests. We do run system level testing however and this particular change has been validated with an overnight test of simulated AMI connects/disconnects (through iptables rules) every minute...

**Pull request merged**
