### PR TITLE
String encoding configurable, where UTF-8 is default

### PR DESCRIPTION
**Pull request by elara-leitstellentechnik**
important for customized manager/user events

### CODE REVIEW

**Comment by bsutton** [comment]
elara, happy to accept a patch to implement encoding however it needs to be done in a way that is backward compatible. 
The current implementation appears to break the api.
Can I suggest that you restore the original method signatures and add your new methods as a secondary option.
Using the original methods should unsure that the default encoding scheme is used.

**Comment by elara-leitstellentechnik** [comment]
Hi bsutton,
thanks for your comments. I've restored the public API which use the default encoding as you suggested.

**Comment by bsutton** [comment]
So happy with the code changes.
Can I ask for one more change?
Can you add comments to the set/get encoding methods.

The comments should not be 'sets the encoding'.
The should explain that the default is utf 8 and why someone might want to /need to change the encoding.

ta.
Brett

**Comment by elara-leitstellentechnik** [comment]
Hi Brett,
I've added comments to the getters/setters and the constructors.

Kind regards, Stefan

**Comment by bsutton** [comment]
thanks for the changes.

**Pull request merged**
