### PR TITLE
Add asterisk 13 field to agent called event

### PR DESCRIPTION
**Pull request by jlebleu**
MemberName replace AgentName, AgentName kept for asterisk 11 support

### CODE REVIEW

**Comment by bsutton** [comment]
Thanks for the update.
Can I get you to make a couple of changes.

remove the AgentName field.

deprecate the get/set agent name methods with appropriate comment to use membername.
change the agentname get/set to use the membername field.

**Comment by jlebleu** [comment]
Hello,
Done.
Means you want to deprecate Asterisk 11 fields ?

**Comment by bsutton** [comment]
essentially yes.

They will still work which is why I want them mapped to the 13 field.

Essentially we need an api that works independently of what version of 
asterisk you are operating on. Having both agent and member means that 
you have to know what version of asterisk you are running against when 
writing your software. The changes I've proposed means that both 11 and 
13 will work seamless with any software that's written.

**Comment by jlebleu** [comment]
Understood,  sounds good to me. Thanks

**Comment by jlebleu** [comment]
Ok I did the changes you may merge when you want

**Comment by jersonjunior** [comment]
I am using the asterisk- java 2.0.0CI with asterisk 13 but can not capture the AgentCalled or MemberName, see logs of eclipse:

ADVERTÊNCIA: Unable to set property 'destcalleridnum' to '1000' on org.asteriskjava.manager.event.AgentCalledEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
out 16, 2015 8:03:16 PM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
ADVERTÊNCIA: Unable to set property 'membername' to 'SIP/1000' on org.asteriskjava.manager.event.AgentCalledEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
***********************	 AgentCalledEvent   ***********************
getChannel 	null
getMember 	null
getMemberName 	null
getQueue 	300
getCallerIDNum 	06182353034
getUniqueId 	1445036592.22
getSource 	ManagerConnection[id='0',hostname='192.168.0.25',port=5038,systemHashcode=1288141870

**Comment by jersonjunior** [comment]
Works fine with jlebleu/asterisk-java!

***********************	 AgentCalledEvent 	 ***********************
getAgentName 	SIP/1000
getQueue 	300
getCallerIDNum 	1001
getUniqueId 	1445184730.0
getSource 	ManagerConnection[id='0',hostname='192.168.0.25',port=5038,systemHashcode=1288141870]
getMemberName 	SIP/1000

:)

**Comment by jlebleu** [comment]
@jersonjunior waiting for @bsutton to be merged in master.
@bsutton should I resubmit this pull request ? I did the changes you requested.
Thanks for your answer

**Comment by bsutton** [comment]
sorry about the delay. Missed this one.

**Comment by bsutton** [comment]
appologises for the delay. I've just merged the code.

**Pull request merged**
