### PR TITLE
Refactor version detection support

### PR DESCRIPTION
**Pull request by nbruning**
Adds proper support for Asterisk 15 up to 15.2.

Removes support for < 1.6 versions, using the 'show file version' method.

Relates to #174

### CODE REVIEW

**Comment by bsutton** [comment]
At this point we are still requiring 1.4 support.
Can you rework so if 'show file version' fails it falls back to the pre 1.6 method.

**Comment by nbruning** [comment]
Are you sure we need to keep supporting Asterisk 1.4? Personally, it feels like a waste of effort.

Asterisk 1.4 was released 12 years ago and has been end-of-life since 2012. If people really want to use 1.4, perhaps they should stick to an older version of AsteriskJava?

**Comment by nbruning** [comment]
Do you want me to rework the patch to drop all support for Asterisk<13 ?
Then this is ready to merge when you start with 3.x.

**Comment by nbruning** [comment]
@bsutton i've merged master into this branch, and removed pre-13 support from the version detection.
Should be ok to merge for 3.x

**Comment by bsutton** [comment]
Thanks for the work :)

**Pull request merged**
