### PR TITLE
Make this project great again

### PR DESCRIPTION
**Pull request by piotrooo**
Linked issue #386 

TODO:

- [x] add GitHub Actions for run tests (CI)
- [x] remove Gradle support
- [x] remove old, unused files
- [x] bump dependencies (e.g.: replacing easymock with mockito - has much more better API)
- [x] add dependabot
- [x] use spaces indentation
- [x] add more tests (right now code is covered in 21%...)

### CODE REVIEW

**Comment by piotrooo** [comment]
Could someone review changes?

**Comment by bsutton** [comment]
Will have a look Monday.

**Comment by piotrooo** [comment]
Any news?
Are you as a current project maintainers (?) interested in that kind of help? Please, could you to be honest, I don't want wasting my time...
I have couple of new ideas, but with that kind of workflow, nothing gonna happen.

**Comment by rlsutton1** [comment]
CI is failing due to java class file version incompatibility,but I am going to merge this anyway.

**Pull request merged**
