### PR TITLE
Don't leak classes that are 'internal'

### PR DESCRIPTION
**Pull request by seanbright**
There were two places that 'internal' classes were being published:

1. AgiChannelFactory is published via AbstractAgiServer and others.
2. AsteriskAgentImpl published via AsteriskServerListener.

So we promote AgiChannelFactory to API - which requires us to also
pull up AgiReader and AgiWriter - and we replace the reference to
AsteriskAgentImpl with AsteriskAgent.

Also updated bnd plugin to 3.2.0

### CODE REVIEW

**Comment by bsutton** [comment]
This is likely to break some code but i think the re-org is worth it and this is the 2.0 release under which we do expect some breakage.

**Comment by seanbright** [comment]
I would guess that it would break very little code as I doubt it is a common extension point. I do think there could be a better separation of API and default/base implementation than what exists now. I'll work on a PR with some ideas. When do you plan to tag 2.0.0?

**Comment by bsutton** [comment]
OK will look out for the PR.
Not certain on when we will tag 2.0.
We have some apis we want to merge in.
These are what we call Activities which provide high level functionality to do common operations. e.g. dial, transfer, answer.... with just a few lines of code. The idea is to remove the need to understand asterisk, events and actions. We are using activities in a project and slowly expanding the set of activities. So we want to merge these activites into the code base before tagging 2.0.
We are also looking for people interested in fleshing out the set of available activities?

**Comment by dondos** [comment]
Because of the [change ](https://maven.apache.org/maven-logging.html) in the logging API, for bnd 3.2.0, you will need at least maven 3.1.0. Otherwise`mvn install` will fail.

**Pull request merged**
